/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/sina/Sites/MrNobody/public/3d/mrnobodytitle.glb -o /Users/sina/Sites/MrNobody/src/MrNobodyTitle.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function MrNobodyTitle(props) {
  const { nodes, materials } = useGLTF('/3d/mrnobodytitle.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Meshy_Mesh_0.geometry} material={materials.Material_0} position={[0, .2, 0]} scale={0.75}/>
      <mesh geometry={nodes.Text.geometry} material={materials['Material.001']} position={[-0.075, 0.05, -1]} rotation={[Math.PI / 2, 0, 0]} scale={0.88} />
    </group>
  )
}

useGLTF.preload('/3d/mrnobodytitle.glb')
