/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/sina/Sites/MrNobody/public/3d/mrnobodytitle.glb -o /Users/sina/Sites/MrNobody/src/MrNobodyTitle.jsx
*/

import * as THREE from 'three'
import { useEffect, useMemo } from 'react'
import { useGLTF } from '@react-three/drei'
import { button, folder, useControls } from 'leva'
import { useLevaStores } from './levaStores'

const MESHY_GLASS_STATE = {
  color: '#ffffff',
  metalness: 0,
  roughness: 0,
  envMapIntensity: 1.5,
  emissive: '#000000',
  emissiveIntensity: 0,
  opacity: 1,
  transparent: true,
  wireframe: false,
  side: THREE.DoubleSide,
  transmission: 1,
  ior: 1.5,
  thickness: 1.5,
  specularIntensity: 1,
  specularColor: '#ffffff',
  clearcoat: 1,
  clearcoatRoughness: 0,
  attenuationColor: '#ffffff',
  attenuationDistance: 50,
  reflectivity: 0.5,
  sheen: 0,
  sheenRoughness: 1,
  sheenColor: '#ffffff',
  useMap: false
}

const SIDE_OPTIONS = { Front: THREE.FrontSide, Back: THREE.BackSide, Double: THREE.DoubleSide }

function sideToLeva(side) {
  if (side === THREE.BackSide) return 'Back'
  if (side === THREE.DoubleSide) return 'Double'
  return 'Front'
}

function cloneAsPhysical(source) {
  const mat = source.isMeshPhysicalMaterial ? source.clone() : new THREE.MeshPhysicalMaterial().copy(source)
  mat.userData.textureMaps = {
    map: mat.map,
    normalMap: mat.normalMap,
    roughnessMap: mat.roughnessMap,
    metalnessMap: mat.metalnessMap,
    aoMap: mat.aoMap,
    emissiveMap: mat.emissiveMap
  }
  return mat
}

function applyTextureMaps(material, enabled) {
  const maps = material.userData.textureMaps
  if (!maps) return
  material.map = enabled ? maps.map : null
  material.normalMap = enabled ? maps.normalMap : null
  material.roughnessMap = enabled ? maps.roughnessMap : null
  material.metalnessMap = enabled ? maps.metalnessMap : null
  material.aoMap = enabled ? maps.aoMap : null
  material.emissiveMap = enabled ? maps.emissiveMap : null
}

function readMaterialState(material) {
  const attenuationDistance =
    !Number.isFinite(material.attenuationDistance) || material.attenuationDistance > 50
      ? 50
      : material.attenuationDistance

  return {
    color: `#${material.color.getHexString()}`,
    metalness: material.metalness ?? 0,
    roughness: material.roughness ?? 1,
    envMapIntensity: material.envMapIntensity ?? 1,
    emissive: `#${material.emissive.getHexString()}`,
    emissiveIntensity: material.emissiveIntensity ?? 0,
    opacity: material.opacity ?? 1,
    transparent: material.transparent ?? false,
    wireframe: material.wireframe ?? false,
    side: material.side ?? THREE.FrontSide,
    transmission: material.transmission ?? 0,
    ior: material.ior ?? 1.5,
    thickness: material.thickness ?? 0,
    specularIntensity: material.specularIntensity ?? 1,
    specularColor: `#${(material.specularColor ?? material.color).getHexString()}`,
    clearcoat: material.clearcoat ?? 0,
    clearcoatRoughness: material.clearcoatRoughness ?? 0,
    attenuationColor: `#${(material.attenuationColor ?? new THREE.Color('#ffffff')).getHexString()}`,
    attenuationDistance,
    reflectivity: material.reflectivity ?? 0.5,
    sheen: material.sheen ?? 0,
    sheenRoughness: material.sheenRoughness ?? 1,
    sheenColor: `#${(material.sheenColor ?? new THREE.Color('#ffffff')).getHexString()}`,
    useMap: Boolean(material.map)
  }
}

function applyMaterialState(material, state) {
  material.color.set(state.color)
  material.metalness = state.metalness
  material.roughness = state.roughness
  material.envMapIntensity = state.envMapIntensity
  material.emissive.set(state.emissive)
  material.emissiveIntensity = state.emissiveIntensity
  material.opacity = state.opacity
  material.transparent = state.transparent || state.transmission > 0
  material.wireframe = state.wireframe
  material.side = state.side
  material.transmission = state.transmission
  material.ior = state.ior
  material.thickness = state.thickness
  material.specularIntensity = state.specularIntensity
  material.specularColor.set(state.specularColor)
  material.clearcoat = state.clearcoat
  material.clearcoatRoughness = state.clearcoatRoughness
  material.attenuationColor.set(state.attenuationColor)
  material.attenuationDistance = state.attenuationDistance >= 50 ? Infinity : state.attenuationDistance
  material.reflectivity = state.reflectivity
  material.sheen = state.sheen
  material.sheenRoughness = state.sheenRoughness
  material.sheenColor.set(state.sheenColor)
  applyTextureMaps(material, state.useMap)
  material.needsUpdate = true
}

function toLevaDefaults(state) {
  return { ...state, side: sideToLeva(state.side) }
}

function physicalMaterialSchema(d, store, resetDefaults) {
  return {
    Base: folder({
      useMap: d.useMap,
      color: d.color,
      metalness: { value: d.metalness, min: 0, max: 1 },
      roughness: { value: d.roughness, min: 0, max: 1 },
      envMapIntensity: { value: d.envMapIntensity, min: 0, max: 5, label: 'Env intensity' }
    }),
    'Transmission & IOR': folder({
      transmission: { value: d.transmission, min: 0, max: 1 },
      ior: { value: d.ior, min: 1, max: 2.5, step: 0.01 },
      thickness: { value: d.thickness, min: 0, max: 5, step: 0.01 },
      reflectivity: { value: d.reflectivity, min: 0, max: 1 },
      attenuationColor: { value: d.attenuationColor, label: 'Attenuation' },
      attenuationDistance: { value: d.attenuationDistance, min: 0, max: 50, step: 0.1, label: 'Atten. distance' }
    }),
    Specular: folder({
      specularIntensity: { value: d.specularIntensity, min: 0, max: 1, label: 'Intensity' },
      specularColor: d.specularColor
    }),
    Clearcoat: folder({
      clearcoat: { value: d.clearcoat, min: 0, max: 1 },
      clearcoatRoughness: { value: d.clearcoatRoughness, min: 0, max: 1, label: 'Clearcoat rough.' }
    }),
    Sheen: folder({
      sheen: { value: d.sheen, min: 0, max: 1 },
      sheenRoughness: { value: d.sheenRoughness, min: 0, max: 1, label: 'Sheen rough.' },
      sheenColor: d.sheenColor
    }),
    Emissive: folder({
      emissive: d.emissive,
      emissiveIntensity: { value: d.emissiveIntensity, min: 0, max: 3, label: 'Intensity' }
    }),
    Advanced: folder({
      opacity: { value: d.opacity, min: 0, max: 1 },
      transparent: d.transparent,
      wireframe: d.wireframe,
      side: { value: d.side, options: SIDE_OPTIONS }
    }),
    Reset: button(() => store.set(resetDefaults, true))
  }
}

const MESHY_LEVA_DEFAULTS = toLevaDefaults(MESHY_GLASS_STATE)

/** Default physical props for the intro / subtitle text mesh (Material.001). */
const INTRO_TEXT_MATERIAL_OVERRIDES = {
  color: '#a00a7b',
  metalness: 0.87,
  roughness: 1,
  envMapIntensity: 1,
  transmission: 0
}

function usePhysicalMaterialControls(store, panelName, levaDefaults) {
  const [state] = useControls(
    panelName,
    () => physicalMaterialSchema(levaDefaults, store, levaDefaults),
    { store }
  )
  return state
}

export function MrNobodyTitle(props) {
  const { meshyStore, titleTextStore } = useLevaStores()
  const { nodes, materials } = useGLTF('/3d/mrnobodytitle.glb')

  const meshMaterial = useMemo(() => {
    const mat = cloneAsPhysical(materials.Material_0)
    applyMaterialState(mat, MESHY_GLASS_STATE)
    return mat
  }, [materials])

  const textMaterial = useMemo(() => {
    const mat = cloneAsPhysical(materials['Material.001'])
    const base = readMaterialState(mat)
    applyMaterialState(mat, { ...base, ...INTRO_TEXT_MATERIAL_OVERRIDES })
    return mat
  }, [materials])

  const textLevaDefaults = useMemo(() => toLevaDefaults(readMaterialState(textMaterial)), [textMaterial])

  const meshyState = usePhysicalMaterialControls(meshyStore, 'Meshy material', MESHY_LEVA_DEFAULTS)
  const textState = usePhysicalMaterialControls(titleTextStore, 'Title text', textLevaDefaults)

  useEffect(() => {
    applyMaterialState(meshMaterial, meshyState)
  }, [meshyState, meshMaterial])

  useEffect(() => {
    applyMaterialState(textMaterial, textState)
  }, [textState, textMaterial])

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Meshy_Mesh_0.geometry} material={meshMaterial} position={[0, 0.3, -2]} scale={2} />
      <mesh
        geometry={nodes.Text.geometry}
        material={textMaterial}
        position={[-0.075, 0.05, -1]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.88}
      />
    </group>
  )
}

useGLTF.preload('/3d/mrnobodytitle.glb')
